name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"   # هيشتغل كل 12 ساعة
  workflow_dispatch:          # تقدر تشغله يدوي من Actions

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ahmedorabii17
          outputs: dist/snake.svg
          palette: tokyonight

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
