name: Generate Snake

on:
  schedule: # كل 12 ساعة
    - cron: "0 */12 * * *"
  workflow_dispatch: # تشغيل يدوي
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ahmedorabii17
          outputs: dist/snake.svg

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate Contribution Snake"
          add: "dist/snake.svg"

      - name: Deploy Snake to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
